@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(player, "Player", "Plays the game")

Container(EntityObject, "Entity Object", "Component", "Game object that interacts with each other")

System_Boundary(c2, "Audios"){
    Container(SoundManager, "Sound Manager", "Component", "Handle all audios in the game")
    Container(SFX, "SFX", "Component", "Handle one shot SFX audio with no loops")
    Container(Music, "Music", "Component", "Handle music audio with loops")
}

Container(Collider, "Collider", "Component", "Data to check if the object is collide or not")

Container(Camera, "Camera", "Component", "Store camera details and return the render output")

Container(GameEngine, "Game Engine", "Component", "Manage current game state and initialize render details")
Container(GameStateController, "Game State Controller", "Component", "handle current level and level transfer")

Container(Renderer, "Renderer", "Component", "Processes the object that requires visualization and textures")

Container(InputSystem, "Input system", "Component", "Manage multiple joystick input")



Container(Level, "Level", "Component", "Manage object rendering and behavior in scenes")

Container(Mesh, "Mesh", "Component", "Handle rendering data for OpenGL")

Rel(player, InputSystem, "input")
Rel(InputSystem, EntityObject, "input actions to the player object")

Rel(EntityObject, Collider, "Uses")

Rel(SoundManager, SFX, "Contains")
Rel(SoundManager, Music, "Contains")

Rel(EntityObject, SoundManager, "Triggers via script")

Rel(Level, EntityObject, "Contains")
Rel(Level, Camera, "Contains")

Rel(GameEngine, Renderer, "Contains")
Rel(GameEngine, GameStateController, "Contains")
Rel(GameStateController, Level, "Contains list of")
Rel(EntityObject, Mesh, "use as a rendering data")


@enduml